import type { McpForgeIR } from "../ir/types.js";

export function generatePackageJson(ir: McpForgeIR): string {
  return JSON.stringify(
    {
      name: ir.server.name,
      version: ir.server.version,
      private: true,
      type: "module",
      scripts: {
        build: "tsup src/index.ts --format esm --dts",
        dev: "tsx watch src/index.ts",
        start: "node dist/index.js"
      },
      dependencies: {
        "@modelcontextprotocol/sdk": "latest",
        dotenv: "latest",
        zod: "latest"
      },
      devDependencies: {
        "@types/node": "latest",
        tsup: "latest",
        tsx: "latest",
        typescript: "latest"
      }
    },
    null,
    2
  );
}

export function generateTsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        declaration: true,
        outDir: "dist"
      },
      include: ["src"]
    },
    null,
    2
  );
}

export function generateReadme(ir: McpForgeIR): string {
  return `# ${ir.server.name}\n\nGenerated by mcpforge.\n\n## Run\n\n\`\`\`bash\npnpm install\npnpm dev\n\`\`\`\n`;
}

export function generateDockerfile(): string {
  return `FROM node:20-alpine\nWORKDIR /app\nCOPY package.json pnpm-lock.yaml* ./\nRUN corepack enable && pnpm install\nCOPY . .\nRUN pnpm build\nCMD [\"node\", \"dist/index.js\"]\n`;
}

export function generateEnvExample(ir: McpForgeIR): string {
  if (!ir.server.auth?.envVariable) {
    return "# No auth env vars required\n";
  }

  return `${ir.server.auth.envVariable}=\n`;
}
